#!/usr/bin/bash
# Author: Ziad Abdelalim
# Title: Case
# Date: 29/01/2024
# Description:

read -r "Enter integer num" num
if [ $num -ge 20 ] && [ $num -le 30 ];
 then   
      printf "%s\n" "Valid Number"
 
 else
  while :  
   do
     read -r "Enter Number between 20 and 30" num 
       $(($num >= 20)) && $(($num <= 30)) && break
   done
fi
