#!/usr/bin/bash
# Author: Ziad Abdelalim
# Title: Case
# Date: 29/01/2024
# Description: Enter number between 20 and 30 if invalid number was entered repeat the process

read -p "Enter integer num" num
if [ $num -ge 20 ] && [ $num -le 30 ];
 then   
      printf "%s\n" "Valid Number"
 
 else
  while :  
   do
     read -p "Enter Number between 20 and 30" num
      if [ $num -ge 20 ] && [ $num -le 30 ];then
          printf "%s\n" "Validnumber"
          break 
        fi 
 done
fi
